baseurl = "https://lucaguidi.com/"
copyright = "All rights reserved - 2021"
disqusshortname = "lucaguidi"
languagecode = "en-US"
[pagination]
pagerSize = 5
pluralizelisttitles = false
theme = "casper"
title = "Luca Guidi"
pygmentsuseclasses  = true
pygmentscodefences  = true
enableGitInfo = true

[[menu.main]]
name = "Twitter"
url = "https://twitter.com/jodosha"
pre = "<h3>Follow me</h3>"
weight = 200
[[menu.main]]
name = "Github"
url = "https://github.com/jodosha"
weight = 190
[[menu.main]]
name = "Keybase"
url = "https://keybase.io/jodosha"
weight = 180
[[menu.main]]
name = "Facebook"
url = "https://www.facebook.com/Luca-Guidi-1603307663019001"
weight = 170
[[menu.main]]
name = "Instagram"
url = "https://www.instagram.com/jodosha/"
weight = 160
[[menu.main]]
name = "YouTube (code)"
url = "https://www.youtube.com/channel/UCAprzjCQpYdzyN9Bv-Iq1sA"
weight = 150
[[menu.main]]
name = "YouTube (music)"
url = "https://www.youtube.com/c/jodosha"
weight = 140
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = 120
[[menu.main]]
name = "Now"
url = "/now"
pre = "<h3>Misc</h3>"
weight = 110
[[menu.main]]
name = "Sponsors"
url = "/sponsors"
weight = 100
[[menu.main]]
name = "Privacy Policy"
url = "/privacy.html"
weight = 90

[params]
  mainSections = ["post"]
  author = "Luca Guidi"
  authorlocation = "Rome, Italy"
  authorwebsite = "https://lucaguidi.com"
  description = "Family man, software architect, Open Source indie developer, speaker."
  authorbio = "Family man, software architect, Open Source indie developer, speaker."
  cover = "images/cover.jpg"
  githubName = "jodosha"
  googleAnalyticsUserID = "UA-235843-4"
  RSSLink = "https://feeds.feedburner.com/LucaGuidi"
  hideHUGOSupport = false
  logo = "images/logo.png"
  twitterName = "jodosha"
  hjsStyle="ocean"

[permalinks]
  fixed = ":title/"
  post = "/:year/:month/:day/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"
