baseurl = "https://lucaguidi.com/"
languageCode = "en-US"
theme = "terminal"
title = "Luca Guidi"
enableGitInfo = true

[pagination]
pagerSize = 5

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
style = ""


[params]
  contentTypeName = "posts"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false
  author = "Luca Guidi"
  authorlocation = "Rome, Italy"
  authorwebsite = "https://lucaguidi.com"
  description = "Family man, senior software architect, Open Source indie developer, speaker."
  authorbio = "Family man, senior software architect, Open Source indie developer, speaker."
  cover = "images/cover.jpg"
  githubName = "jodosha"
  googleAnalyticsUserID = "UA-235843-4"
  RSSLink = "/rss.xml"
  hideHUGOSupport = false
  logo = "images/logo.png"
  twitterName = "jodosha"
  hjsStyle="ocean"

[languages]
  [languages.en]
    title = "Luca Guidi"
    subtitle = "Family man, senior software architect, Open Source indie developer, speaker."
    keywords = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Luca Guidi"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "now"
        name = "What I'm Doing Now"
        url = "/now"

[permalinks]
  fixed = ":title/"
  posts = "/:year/:month/:day/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    baseName = "rss"
    mediaType = "application/rss+xml"

[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"
