source 'https://rubygems.org'
ruby '2.3.3'

gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'maruku'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'nokogiri'
gem 'github-pages'
gem 'pygments.rb'
